# Generated by Django 5.1 on 2024-08-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(verbose_name='Rating position')),
                ('player', models.CharField(max_length=256, verbose_name='Username')),
                ('level', models.PositiveIntegerField(verbose_name='Player level')),
                ('ingame', models.PositiveIntegerField(verbose_name='In-game days')),
                ('region', models.CharField(max_length=4, verbose_name='Rating region')),
            ],
            options={
                'verbose_name': 'Rating',
                'db_table': 'core_rating',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish', models.CharField(max_length=64, verbose_name='Fish name')),
                ('weight', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Fish weight')),
                ('location', models.CharField(max_length=64, verbose_name='Location')),
                ('lure', models.CharField(max_length=128, verbose_name='Lure name')),
                ('player', models.CharField(max_length=256, verbose_name='Username')),
                ('date', models.DateField(verbose_name='Date of catch')),
                ('region', models.CharField(max_length=4, verbose_name='Record region')),
            ],
            options={
                'verbose_name': 'Record',
                'db_table': 'core_records',
                'ordering': ['id'],
            },
        ),
    ]
