# Generated by Django 5.1 on 2024-10-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbsoluteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=3, max_digits=16, verbose_name='Fish weight')),
                ('fish', models.CharField(max_length=64, verbose_name='Fish name')),
                ('location', models.CharField(max_length=64, verbose_name='Location')),
                ('bait', models.CharField(max_length=128, verbose_name='Bait name')),
                ('player', models.CharField(max_length=256, verbose_name='Username')),
                ('date', models.DateField(verbose_name='Date of catch')),
                ('region', models.CharField(max_length=4, verbose_name='Record region')),
                ('category', models.CharField(max_length=16, verbose_name='Record type')),
            ],
            options={
                'verbose_name': 'Absolute Record',
                'db_table': 'core_absolute_records',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(verbose_name='Rating position')),
                ('level', models.PositiveIntegerField(verbose_name='Player level')),
                ('ingame', models.PositiveIntegerField(verbose_name='In-game days')),
                ('region', models.CharField(max_length=4, verbose_name='Rating region')),
                ('player', models.CharField(max_length=256, verbose_name='Username')),
            ],
            options={
                'verbose_name': 'Rating',
                'db_table': 'core_rating',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=3, max_digits=16, verbose_name='Fish weight')),
                ('fish', models.CharField(max_length=64, verbose_name='Fish name')),
                ('location', models.CharField(max_length=64, verbose_name='Location')),
                ('bait', models.CharField(max_length=128, verbose_name='Bait name')),
                ('player', models.CharField(max_length=256, verbose_name='Username')),
                ('date', models.DateField(verbose_name='Date of catch')),
                ('region', models.CharField(max_length=4, verbose_name='Record region')),
                ('category', models.CharField(max_length=16, verbose_name='Record type')),
            ],
            options={
                'verbose_name': 'Weekly Record',
                'db_table': 'core_weekly_records',
            },
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(verbose_name='Rating position')),
                ('records', models.PositiveIntegerField(verbose_name='Records count')),
                ('score', models.PositiveIntegerField(verbose_name='Score')),
                ('player', models.CharField(max_length=256, verbose_name='Username')),
                ('prize', models.CharField(blank=True, max_length=256, verbose_name='Prize')),
                ('region', models.CharField(max_length=4, verbose_name='Record region')),
                ('category', models.CharField(max_length=16, verbose_name='Record category')),
            ],
            options={
                'verbose_name': 'Winner',
                'db_table': 'core_winners',
                'ordering': ['id'],
            },
        ),
    ]
